### ISSUE TITLE
why the LoadMoreMessagesListener is synchronous?

### ISSUE THREAD

**Issue by Axolot1** [Slyce-Inc/SlyceMessaging#12]
In practice, loadMoreMessages() will trigger a http request or a db operation to get more data. So i think it would be better if there is a asynchronous way.

**Comment by MatthewPageCS** [comment]
Good idea! I'll work on this and get it in the next release.

**Comment by MatthewPageCS** [comment]
Just created version 1.0.4, this should solve the issue.

**Comment by sourabhbans007** [comment]
i think you forgot the .execute() method of AsyncTask.

**Comment by MatthewPageCS** [comment]
@sourabhbans007 good catch, I tested it incorrectly before I shipped it. 

I've reverted the README to version 1.0.3 for now. Executing the AsyncTask causes a weird exception, I'll look into it.

**Comment by sourabhbans007** [comment]
RecyclerView: Inconsistency detected. Invalid item position
i think.. :)

**Comment by MatthewPageCS** [comment]
^ Yep, that was caused by the RecyclerView being updated while being scrolled at the same time. Fixed, version 1.0.5 should have this issue solved.
