### ISSUE TITLE
Handling Participants

### ISSUE THREAD

**Issue by pixelbendr** [Slyce-Inc/SlyceMessaging#15]
Your App is really cool, helped me make a lot of decisions on mine. Wanted to find out how to handle a two way chat with the ability to add more later. Like a channel of two users that allows me to add more users later. Hope am making sense. Regards.

**Comment by MatthewPageCS** [comment]
Hi! 

Our current intention is for you to simply provide add Message objects to the fragment. Different external users are differentiated by different user IDs and different avatar URL's. When there's a new message in the list that's authored by a different user than the preceding message, even if both messages are from an external user, the new message should be considered part of a new sequence (with an avatar indicating who it is).

Does this answer your question?

**Comment by MatthewPageCS** [comment]
I'm going to close his for now. Feel free to reopen if needed.
