### ISSUE TITLE
Localize texts

### ISSUE THREAD

**Issue by eabait** [Slyce-Inc/SlyceMessaging#25]
Hi

I'm trying to localize my app, and I cant find the way to localize some text in Slyce views, like: "Just now", "Text copied", etc

Do you have any config I can change?

Thanks!
Esteban

**Comment by eabait** [comment]
I have forked the project. I'll try to send a PR by tomorrow

**Comment by jchunchar** [comment]
@eabait -- sorry for the delay. Looks good, just merged.
